categories:
  - Food
  - Clothing
  - Travel
  - Entertainment
  - Utilities
  - Healthcare
  - Education
  - Car Expenses
  - Insurance
  - Gifts
  - Shopping
  - Baby Stuff
  - Home Improvement
  - Advertising
  - Hobbies
  - Personal Care
  - Bank Fees
  - Fines
  - Other